### ISSUE TITLE
Fuzzy search

### ISSUE THREAD

**Issue by djadomi** [composablehorizons/composeicons#4]
It'd be nice if the search was a bit more "natural" - for example, searching for "arrow up" returns nothing; "arrow-up" returns a few collections; "arrow_up" gets only Material… these should all return the same.

**Comment by djadomi** [comment]
And "arrow_up" doesn't get Material's "arrow_circle_up" which would also be included by "arrow up", ideally.

**Comment by alexstyl** [comment]
i agree. right now it's exact text iirc. this would be a nice addition

**Comment by djadomi** [comment]
Cool, what I should have started off with was: "nice work, _very_ handy, thanks".

**Comment by alexstyl** [comment]
it's cool. i appreciate the fact that you are using my site, let alone opening an issue :)

**Comment by alexstyl** [comment]
@djadomi just pushed an update. can you try it out and let me know how it is?

**Comment by alexstyl** [comment]
updated. try one more time https://composeicons.com/

**Comment by djadomi** [comment]
Super cool! I think these changes easily satisfy this current enhancement request. Nice one.
